Fix typos and update some complicated sentences
Maoni0/mem-doc pull request #3
Opened 2020-09-10 20:42 UTC by chrisnas

Great content @Maoni0!
I've tried to fix a few typos and also did some changes in complicated sentences.

I don't think this PR could be "merged" like code because you might disagree on some of my changes. But at least you could use it to fix the typos   :^)

I will create other issues in paragraphs in which I'm lost or I'm using different solutions

I hope this helps...

2020-09-10 22:52 UTC, Maoni0 commented on doc/.NETMemoryPerformanceAnalysis.md
> +Network IO is just an example of another factor that could contribute to your request latency. And boxe widths here are merely for illustration purpose.
boxe -> box?

2020-09-10 22:56 UTC, Maoni0 commented on doc/.NETMemoryPerformanceAnalysis.md
> +A garbage collector provides the great benefit of memory safety, frees developers from having to manually free memory and saves possibly months or years of debugging memory leaks and even worse: heap
I would avoid saying "debugging memory leaks" because you can still have memory leaks with a garbage collector.

2020-09-10 22:58 UTC, Maoni0 commented on doc/.NETMemoryPerformanceAnalysis.md
> +If the total private committed bytes (as mentioned above the GC heap is always in private memory) of a process is pretty close to your GC heap's committed bytes, you know most of it is due to the GC
I specifically didn't want to say "native" here because you could have other non native memory usage - for example, you could have java code in the same process and it also has a GC heap.

2020-09-11 00:39 UTC, Maoni0 commented on doc/.NETMemoryPerformanceAnalysis.md
> +The .NET GC is [generational](https://en.wikipedia.org/wiki/Tracing_garbage_collection#Generational_GC_(ephemeral_GC)) with 3 generations, IOW, the GC heap is divided into 3 generations; gen0 is the
"gen0 is the generation containing the youngest objects that never had to survive a collection" - this is incorrect; you can have objects in gen0 that have survived collections. 

"objects in gen2 are the old ones that survived at least two collections." - this is also incorrect, large objects are part of gen2 but they don't need to have survived any collections.

2020-09-11 00:40 UTC, Maoni0 commented on doc/.NETMemoryPerformanceAnalysis.md
> +Most of the time you don't have to be concerned with the fact the GC heap is organized into segments except on 32-bit since the virtual address space is small (2GB-3GB total) and can be fragmented, e
it's 4GB - you get 4GB when you enable large address aware for a 32-bit process on 64-bit.

2020-09-11 00:41 UTC, Maoni0 commented on doc/.NETMemoryPerformanceAnalysis.md
> +As mentioned before, in [high memory load](#GC-is-per-process-but-is-aware-of-physical-memory-load-on-the-machine) situations we are more aggressive at triggering gen2 blocking GCs. When the memory l
it's not necessarily the OS - you could be in a container; or you config it so that GC thinks it's short on memory.  if you really want to change it, you could change it to "when GC thinks it's short on memory"

2020-09-11 00:47 UTC, Maoni0 commented on doc/.NETMemoryPerformanceAnalysis.md
> +One last part of the GC pauses we haven’t mentioned is the part that’s not doing the GC work at all - I'm referring to the thread suspension mechanism in the runtime. GC calls the suspension mechanis
"execution engine" is not a concept that has been introduced... if you want to change I would probably change it to "calls the suspension mechanism"...whether it's part of the EE or not is not really relevant here...

2020-09-11 00:51 UTC, Maoni0 commented on doc/.NETMemoryPerformanceAnalysis.md
> +% CPU time in GC can be more or less than % Pause time in GC, even when BGC is not in the picture, because it depends on how CPU is used by other things in the process. When GC is in progress, we wou
> we would like to see it finish as fast as possible; so probably having as high CPU usage as possible during its execution.

I would not say "probably" - this is a case where we should be accurate so if you want add that part I would say 

> we would like to see it finish as fast as possible; so we'd like to see it have as high CPU usage as possible during its execution.

2020-09-11 00:55 UTC, Maoni0 commented on doc/.NETMemoryPerformanceAnalysis.md
> +Another challenge with picking the right tools is unless you are doing a basic analysis, there simply aren’t many tools to choose from. IOW, there are a lot more tools that are able to solve simple p
> you will be able to easily find a tool  that can compare heap snapshots and what’s left in these leaky snapshots that should not be here.

I would rewrite this to 

> you will be able to easily find a tool that can compare heap snapshots so you can see what objects survived that shouldn't.

2020-09-11 00:57 UTC, Maoni0 commented on doc/.NETMemoryPerformanceAnalysis.md
> +The tool the runtime team produces and what I use often is [PerfView](https://github.com/microsoft/perfview/) – many of you probably have heard of it. But I haven’t seen many people use it to its ful
> They share the same format so events

I would add an "and" here so it emphasizes the same format part which is what I really want to say here -

> And they share the same format so events

2020-09-11 00:59 UTC, Maoni0 commented on doc/.NETMemoryPerformanceAnalysis.md
> +Since now .NET Core is cross-plat, and ETW does not exist on Linux, we have other eventing mechanisms that aim to make this process transparent such as LTTng or EventPipe. Anyway, if you use the Trac
> such as LTTng or EventPipe. Anyway,

I would suggest changing this to 

> such as LTTng or EventPipe. So

"Anyway" sounds weird here.

2020-09-11 01:04 UTC, Maoni0 commented on doc/.NETMemoryPerformanceAnalysis.md
> +You might also have used our debugger extension [SoS](https://docs.microsoft.com/en-us/dotnet/framework/tools/sos-dll-sos-debugging-extension). I rarely use SoS for perf analysis because it’s much mo
> you might want to dump and analyze them with [dotnet-dump](https://github.com/dotnet/diagnostics/blob/master/documentation/dotnet-dump-instructions.md) that provides SoS commands (and more).

I would suggest to change to 

> you can get the [dotnet-dump](https://github.com/dotnet/diagnostics/blob/master/documentation/dotnet-dump-instructions.md) tool which produces a dump that you can run SoS commands on.

2020-09-11 01:10 UTC, Maoni0 commented on doc/.NETMemoryPerformanceAnalysis.md
> +![GCStats](gcstats.jpg)
so I do want the zoom:80% part 'cause it looks better. but I dunno how to get GH to recognize this. in Typora this is scaled to 80%. do you know how? :P

2020-09-11 01:13 UTC, Maoni0 commented on doc/.NETMemoryPerformanceAnalysis.md
> +Double clicking on the name of an event shows all the occurrences of that event. In the process, it loads all events in which you can search for specific details. For example, if I want to find out t
>  In the process, it loads all events in which you can search for specific details.

suggested edit - 

> You can search for specific details.

2020-09-11 01:14 UTC, Maoni0 commented on doc/.NETMemoryPerformanceAnalysis.md
> +Then you can see the exact version info of the coreclr.dll you are using. Remember, if you don't load the events you are interested in, the search will fail.
> Remember, if you don't load the events you are interested in, the search will fail.

I think this is quite obvious? If you search, you search in things that are displayed..

2020-09-11 01:18 UTC, Maoni0 commented on doc/.NETMemoryPerformanceAnalysis.md
> +“Max Dump K Objs” is an attempt to be “smart” so it doesn’t dump every single object. I always increase it to at least 10x the default value 250. And the Freeze option is there for production diagnos
> the default value 250

suggested edit

> the default value (250)

2020-09-11 01:19 UTC, Maoni0 requested changes
thanks so much! I've suggested some edits of your edits :)

2020-09-11 07:17 UTC, chrisnas commented on doc/.NETMemoryPerformanceAnalysis.md
> +The .NET GC is [generational](https://en.wikipedia.org/wiki/Tracing_garbage_collection#Generational_GC_(ephemeral_GC)) with 3 generations, IOW, the GC heap is divided into 3 generations; gen0 is the
I'm not sure pinned objects or LOH are related to the notion of generational GC you are introducing here. I made this change because the notion of "youngest" or "old" generation is not self explanatory. I'm trying a new update and you will check  :^)

2020-09-11 07:21 UTC, chrisnas commented on doc/.NETMemoryPerformanceAnalysis.md
> +Most of the time you don't have to be concerned with the fact the GC heap is organized into segments except on 32-bit since the virtual address space is small (2GB-3GB total) and can be fragmented, e
My mistake

2020-09-11 07:33 UTC, chrisnas commented on doc/.NETMemoryPerformanceAnalysis.md
> +You might also have used our debugger extension [SoS](https://docs.microsoft.com/en-us/dotnet/framework/tools/sos-dll-sos-debugging-extension). I rarely use SoS for perf analysis because it’s much mo
Both are done by the same tool: you don't need WinDBG even on Windows. I'm updating the sentence to make it more explicit:
> you can get the dotnet-dump tool to both produce a dump and analyze it thanks to SoS and higher level commands

2020-09-11 07:43 UTC, chrisnas commented on doc/.NETMemoryPerformanceAnalysis.md
> +![GCStats](gcstats.jpg)
It does not seem to be possible...
I changed the HTML syntax because in my markdown extension in Chrome, the text was glued to the picture so I tried to fix it
![image](https://user-images.githubusercontent.com/10163781/92885626-3b9e2f80-f413-11ea-88ca-4178ff929fc4.png)

but it is not the case in github. Sorry about that.

2020-09-11 07:47 UTC, chrisnas commented on doc/.NETMemoryPerformanceAnalysis.md
> +Double clicking on the name of an event shows all the occurrences of that event. In the process, it loads all events in which you can search for specific details. For example, if I want to find out t
I don't know how to say that if you don't double click, the find won't work... I tried to add it after the picture but it did not looks great. Maybe I can just add "then" to make it more explicit:
> Then, you can search for specific details. For example...

if you have a better idea...

2020-09-11 07:50 UTC, chrisnas commented on doc/.NETMemoryPerformanceAnalysis.md
> +Then you can see the exact version info of the coreclr.dll you are using. Remember, if you don't load the events you are interested in, the search will fail.
It was not for me  :^)
I'm removing it (I hope the previous update will make it useless)

2020-09-12 01:37 UTC, Maoni0 commented
@chrisnas please let me know when you are ready for another review. thanks!

2020-09-12 09:22 UTC, chrisnas commented
> @chrisnas please let me know when you are ready for another review. thanks!

@Maoni0 If you don't merge my PR, I won't be able to "see" your new changes  :^(

2020-09-13 08:27 UTC, chrisnas commented
@Maoni0 I have merged your changes and the first PR so you could check if the result is fine

2020-09-15 00:48 UTC, Maoni0 commented on doc/.NETMemoryPerformanceAnalysis.md
> +Network IO is just an example of another factor that could contribute to your request latency. And boxe widths here are merely for illustration purpose.
this is still not changed?

2020-09-15 00:53 UTC, Maoni0 commented on doc/.NETMemoryPerformanceAnalysis.md
> +One last part of the GC pauses we haven’t mentioned is the part that’s not doing the GC work at all - I'm referring to the thread suspension mechanism in the runtime. GC calls the suspension mechanis
> and get your threads to stop
->
> to get your threads to stop

2020-09-15 00:56 UTC, Maoni0 commented on doc/.NETMemoryPerformanceAnalysis.md
> +You might also have used our debugger extension [SoS](https://docs.microsoft.com/en-us/dotnet/framework/tools/sos-dll-sos-debugging-extension). I rarely use SoS for perf analysis because it’s much mo
> SoS and higher level commands.

which high level commands are you referring to here?

2020-09-15 05:33 UTC, chrisnas commented on doc/.NETMemoryPerformanceAnalysis.md
> +One last part of the GC pauses we haven’t mentioned is the part that’s not doing the GC work at all - I'm referring to the thread suspension mechanism in the runtime. GC calls the suspension mechanis
fixed

2020-09-15 05:37 UTC, chrisnas commented on doc/.NETMemoryPerformanceAnalysis.md
> +You might also have used our debugger extension [SoS](https://docs.microsoft.com/en-us/dotnet/framework/tools/sos-dll-sos-debugging-extension). I rarely use SoS for perf analysis because it’s much mo
I'm referring to the commands I added to get the state of the threads, thread pool, timers and tasks.
Let's make it more explicit.

2020-09-15 05:38 UTC, chrisnas commented
> aside from the 2 minor comments above and boxe, the rest looks good to me!

I fixed "boxe" and took into account your 2 comments

2020-09-15 07:47 UTC, Maoni0 commented on doc/.NETMemoryPerformanceAnalysis.md
> +You might also have used our debugger extension [SoS](https://docs.microsoft.com/en-us/dotnet/framework/tools/sos-dll-sos-debugging-extension). I rarely use SoS for perf analysis because it’s much mo
> I'm referring to the commands I added to get the state of the threads, thread pool, timers and tasks.

sorry I'm still unclear what this sentence means - high level sos commands to get the state of threads, thread pool, timers and tasks, or some other high level commands to get them?

> I'm planning to add GC specific commands such as listing pinned objects and a "dumpheap -stat " gen could be 0, 1, 2, LOH, POH: would that make sense to you?

you mean that as a totally separate workitem right? not related to mem-doc. that seems fine to me, but I would suggest to open an issue in the dotnet/diagnostics repo to inform the diagnostics folks first.

2020-09-15 09:14 UTC, chrisnas commented on doc/.NETMemoryPerformanceAnalysis.md
> +You might also have used our debugger extension [SoS](https://docs.microsoft.com/en-us/dotnet/framework/tools/sos-dll-sos-debugging-extension). I rarely use SoS for perf analysis because it’s much mo
dotnet-dump provides SoS commands by default. For most users, these are low level commands. When you troubleshoot an issue, you usually need to know what the threads are doing a la Parallel Stacks in VS, check what is running/pending in ThreadPool/Timers, or detailed split of type instances in generations: these are higher level commands. 

> you mean that as a totally separate workitem right? not related to mem-doc. that seems fine to me, but I would suggest to open an issue in the dotnet/diagnostics repo to inform the diagnostics folks first.
yes: a separate discussion topic that will end up in an issue in dotnet/diagnostics.

2020-09-15 20:34 UTC, chrisnas commented
I removed my confusing statement about dotnet-dump so everything should be fine now

2020-09-15 21:25 UTC, merged

2020-09-15 21:26 UTC, Maoni0 commented
thanks so much @chrisnas, I really appreciate it!